image: Visual Studio 2017
clone_folder: c:\dev\supernova
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build_script:
 - echo build_script
 - cmake . -A x64 -B .build
 - cmake --build .build
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
