language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libxrandr-dev
      - libudev-dev
      - g++-7
      - libgl1-mesa-dev
      

env: 
  - CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 GCOV=/usr/bin/gcov-7 CMAKE_OPTIONS="-DENABLE_COVERAGE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"

before_script:
  - sudo -H pip install coverage

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - cmake $CMAKE_OPTIONS .
  - cmake --build .

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

