language: cpp
sudo: required
os: linux
dist: trusty

env: 
  - CXX_EXE=/usr/bin/g++-8 CC_EXE=/usr/bin/gcc-8 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE:STRING=Debug"

branches:
  only:
    - master
    
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - g++-8

before_script:
- sudo apt-get install 

install:
  - export VK_VERSION=1.1.101.0
  - wget -O vulkansdk-linux-x86_64-$VK_VERSION.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/$VK_VERSION/x86_64

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - cmake $CMAKE_OPTIONS .
  - cmake --build .

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

