language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libxrandr-dev
      - libudev-dev
      - g++-7
      - libgl1-mesa-dev
      

env: 
  - CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 GCOV=/usr/bin/gcov-7 CMAKE_OPTIONS="-DENABLE_COVERAGE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"

before_script:
  - sudo -H pip install coverage

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - cmake $CMAKE_OPTIONS .
  - cmake --build .

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/558354787435937831/5I-lcb0OuRnRla0u5_mSbMVOf77p0mD2zvoW3fMFn1yQVlHkdaJkM3Q5rOLdv5W0UXJE
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false



