language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      

env: 
  - CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE:STRING=Debug"

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - cmake .
  - cmake --build .

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

